# Generated by Django 3.2.5 on 2021-07-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='student name')),
                ('bootcamp', models.CharField(max_length=10, verbose_name='bootcamp type')),
                ('camp_date', models.DateTimeField(verbose_name='bootcamp date')),
            ],
        ),
    ]
