# Generated by Django 3.2.5 on 2021-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bootcamp',
        ),
        migrations.AddField(
            model_name='booking',
            name='bootcamp_month',
            field=models.CharField(default='Live', max_length=10, verbose_name='bootcamp month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='bootcamp_type',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOTE', 'Remote')], default='Live', max_length=7, verbose_name='bootcamp_type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='camp_date',
            field=models.CharField(max_length=10, verbose_name='bootcamp date'),
        ),
    ]
