# Generated by Django 3.2.5 on 2021-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210719_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='student name')),
                ('bootcamp_type', models.CharField(choices=[('LIVE', 'Live'), ('REMOTE', 'Remote')], default='Live', max_length=7, verbose_name='bootcamp_type')),
                ('bootcamp_month', models.CharField(max_length=10, verbose_name='bootcamp month')),
                ('camp_date', models.CharField(max_length=10, verbose_name='bootcamp date')),
            ],
        ),
        migrations.CreateModel(
            name='Dbn_bokking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='student name')),
                ('bootcamp_type', models.CharField(choices=[('LIVE', 'Live'), ('REMOTE', 'Remote')], default='Live', max_length=7, verbose_name='bootcamp_type')),
                ('bootcamp_month', models.CharField(max_length=10, verbose_name='bootcamp month')),
                ('camp_date', models.CharField(max_length=10, verbose_name='bootcamp date')),
            ],
        ),
    ]
