# Generated by Django 3.2.5 on 2021-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_johannesburg_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='johannesburg_booking',
            name='name',
            field=models.CharField(max_length=55, verbose_name='student name'),
        ),
    ]
