# Generated by Django 3.2.5 on 2021-07-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_johannesburg_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='johannesburg_booking',
            old_name='name',
            new_name='user',
        ),
    ]
