# Generated by Django 3.2.5 on 2021-07-30 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_rename_name_johannesburg_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cape_town_booking',
            name='bootcamp_month',
        ),
        migrations.RemoveField(
            model_name='cape_town_booking',
            name='camp_date',
        ),
        migrations.RemoveField(
            model_name='cape_town_booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cape_town_booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='durban_booking',
            name='bootcamp_month',
        ),
        migrations.RemoveField(
            model_name='durban_booking',
            name='camp_date',
        ),
        migrations.RemoveField(
            model_name='durban_booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='durban_booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='johannesburg_booking',
            name='bootcamp_month',
        ),
        migrations.RemoveField(
            model_name='johannesburg_booking',
            name='camp_date',
        ),
        migrations.RemoveField(
            model_name='johannesburg_booking',
            name='email',
        ),
        migrations.AddField(
            model_name='cape_town_booking',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='durban_booking',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('moth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.month')),
            ],
        ),
        migrations.AddField(
            model_name='cape_town_booking',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.date'),
        ),
        migrations.AddField(
            model_name='cape_town_booking',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.month'),
        ),
        migrations.AddField(
            model_name='durban_booking',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.date'),
        ),
        migrations.AddField(
            model_name='durban_booking',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.month'),
        ),
        migrations.AddField(
            model_name='johannesburg_booking',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.date'),
        ),
        migrations.AddField(
            model_name='johannesburg_booking',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.month'),
        ),
    ]
