# Generated by Django 3.2.6 on 2021-08-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210730_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='moth',
            new_name='month',
        ),
    ]
