# Generated by Django 3.2.6 on 2021-08-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_rename_moth_date_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='johannesburg_booking',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.date'),
        ),
        migrations.AlterField(
            model_name='johannesburg_booking',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.month'),
        ),
    ]
