# Generated by Django 3.2.6 on 2021-08-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210802_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cape_town_booking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='durban_booking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='johannesburg_booking',
            name='month',
        ),
    ]
