# Generated by Django 3.2.6 on 2021-08-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0016_auto_20210804_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=12)),
                ('bootcamp_type', models.CharField(choices=[('LIVE', 'Live'), ('REMOTE', 'Remote')], default='Live', max_length=7, verbose_name='bootcamp_type')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
