# Generated by Django 3.2.6 on 2021-08-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_allbookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllBookings',
        ),
    ]
